# Generated by Django 2.1 on 2018-12-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vettedproj', '0004_auto_20181207_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('is_admin', 'Can add and remove employees'),)},
        ),
    ]
