# Generated by Django 2.1 on 2018-12-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vettedproj', '0003_auto_20181206_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('view_employees', 'Can view employees'), ('remove_employees', 'Can remove employee'))},
        ),
    ]
